# Generated by Django 4.2.5 on 2023-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginlog',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
