# Generated by Django 4.2.5 on 2023-09-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_user_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
    ]
