# Generated by Django 4.2.5 on 2023-09-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token_requested',
        ),
    ]
