# Generated by Django 4.2.5 on 2023-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
