# Generated by Django 4.2.5 on 2023-09-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_project_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
